services:
  moviebrowser-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: moviebrowser-frontend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - moviebrowser-network

networks:
  moviebrowser-network:
    driver: bridge
